# Generated by Django 2.2.5 on 2019-11-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_book_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='instock',
            new_name='in_stock',
        ),
    ]
